spring:
  application:
    name: azure-exporter
  config:
    import: "optional:configserver:"
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

resource-discovery:
  interval-in-millis: 450000
  initial-delay-millis: 500

scrape:
  interval-in-millis: 300000
  query-window-in-millis: 600000
  initial-delay-millis: 5000
  resourceTypeConfigs:
    - resourceType: "Microsoft.Storage/storageAccounts"
      granularity-in-mins: 5
      metrics:
        - "Ingress"
        - "Availability"
    - resourceType: "Microsoft.Storage/storageAccounts"
      granularity-in-mins: 60
      metrics:
        - "UsedCapacity"
    - resourceType: "Microsoft.Compute/VirtualMachines"
      granularity-in-mins: 5
      metrics:
        - "CPU"
        - "VmAvailabilityMetric"
        - "Available Memory Bytes"
        - "Percentage CPU"
        - "Network Out Total"
        - "Network In Total"
        - "OS Disk Bandwidth Consumed Percentage"
        - "Data Disk Max Burst Bandwidth"
        - "Data Disk IOPS Consumed Percentage"
        - "Data Disk Bandwidth Consumed Percentage"
        - "Data Disk Write Bytes/Sec"
        - "Data Disk Read Bytes/Sec"
        - "CPU Credits Remaining"
        - "Disk Write Bytes"
        - "Disk Read Bytes"
        - "Network Out"
        - "Network In"
    - resourceType: "Microsoft.Network/virtualNetworks"
      granularity-in-mins: 5
      metrics:
        - "IfUnderDDoSAttack"
        - "PingMeshAverageRoundtripMs"
