spring:
  application:
    name: azure-exporter
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri:
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

resource-discovery:
  interval-in-millis: 450000
  initial-delay-millis: 500

scrape:
  interval-in-millis: 300000
  query-window-in-millis: 600000
  initial-delay-millis: 5000
  resourceTypeConfigs:
    - resourceType: "Microsoft.Storage/storageAccounts"
      granularity-in-mins: 5
      metrics:
        - "Ingress"
        - "Availability"
        - "SuccessE2ELatency"
        - "Egress"
        - "Ingress"
        - "Transactions"
    - resourceType: "Microsoft.Storage/storageAccounts"
      granularity-in-mins: 60
      metrics:
        - "UsedCapacity"
    - resourceType: "Microsoft.Compute/VirtualMachines"
      granularity-in-mins: 5
      metrics:
        - "Percentage CPU"
        - "VmAvailabilityMetric"
        - "Available Memory Bytes"
        - "Percentage CPU"
        - "Network Out Total"
        - "Network In Total"
        - "OS Disk Bandwidth Consumed Percentage"
        - "Data Disk Max Burst Bandwidth"
        - "Data Disk IOPS Consumed Percentage"
        - "Data Disk Bandwidth Consumed Percentage"
        - "Data Disk Write Bytes/Sec"
        - "Data Disk Read Bytes/Sec"
        - "CPU Credits Remaining"
        - "Disk Write Bytes"
        - "Disk Read Bytes"
        - "Network Out"
        - "Network In"
    - resourceType: "Microsoft.Network/virtualNetworks"
      granularity-in-mins: 5
      metrics:
        - "IfUnderDDoSAttack"
        - "PingMeshAverageRoundtripMs"
    - resourceType: "Microsoft.Network/applicationGateways"
      granularity-in-mins: 5
      metrics:
        - "AzwafTotalRequests"
        - "BackendLastByteResponseTime"
        - "BackendFirstByteResponseTime"
        - "BackendConnectTime"
        - "ApplicationGatewayTotalTime"
        - "BytesReceived"
        - "BytesSent"
        - "BackendResponseStatus"
        - "ResponseStatus"
        - "NewConnectionsPerSecond"
        - "CurrentConnections"
        - "FailedRequests"
        - "TotalRequests"
        - "HealthyHostCount"
        - "UnhealthyHostCount"
        - "Throughput"
    - resourceType: "Microsoft.Compute/disks"
      granularity-in-mins: 5
      metrics:
        - "Composite Disk Write Bytes/sec"
        - "Composite Disk Read Bytes/sec"
        - "DiskPaidBurstIOPS"
    - resourceType: "Microsoft.ContainerRegistry/registries"
      granularity-in-mins: 5
      metrics:
        - "SuccessfulPushCount"
        - "TotalPushCount"
        - "SuccessfulPullCount"
        - "TotalPullCount"
    - resourceType: "Microsoft.ContainerRegistry/registries"
      granularity-in-mins: 60
      metrics:
        - "StorageUsed"
    - resourceType: "Microsoft.DBforMySQL/flexibleServers"
      granularity-in-mins: 5
      metrics:
        - "HA_SQL_status"
        - "HA_IO_status"
        - "Replica_SQL_Running"
        - "Replica_IO_Running"
        - "serverlog_storage_percent"
        - "storage_throttle_count"
        - "Slow_queries"
        - "Com_delete"
        - "Com_insert"
        - "Com_update"
        - "Com_select"
        - "cpu_credits_remaining"
        - "replication_lag"
        - "storage_percent"
        - "storage_io_count"
        - "io_consumption_percent"
        - "Queries"
        - "aborted_connections"
        - "total_connections"
        - "active_connections"
        - "network_bytes_ingress"
        - "network_bytes_egress"
        - "memory_percent"
        - "cpu_percent"
