management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

resource-discovery:
  interval-in-millis: 300000
  initial-delay-millis: 500

scrape:
  interval-in-millis: 60000
  query-window-in-millis: 600000
  initial-delay-millis: 5000
  resourceTypeConfigs:
    - resourceType: "Microsoft.Storage/storageAccounts"
      granularity-in-mins: 5
      metrics:
        - "Ingress"
        - "Availability"
    - resourceType: "Microsoft.Storage/storageAccounts"
      granularity-in-mins: 60
      metrics:
        - "UsedCapacity"
    - resourceType: "Microsoft.Compute/VirtualMachines"
      granularity-in-mins: 5
      metrics:
        - "CPU"
    - resourceType: "Microsoft.Network/virtualNetworks"
      granularity-in-mins: 5
      metrics:
        - "IfUnderDDoSAttack"
