management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

resource-discovery:
  interval-in-millis: 300000
  initial-delay-millis: 500

scrape:
  interval-in-millis: 60000
  initial-delay-millis: 5000
  granularity-in-mins: 5
  resourceTypeConfigs:
    - resourceType: "Microsoft.Storage/storageAccounts"
      metrics:
        - "Availability"
        - "Ingress"
    - resourceType: "Microsoft.Compute/VirtualMachines"
      metrics:
        - "CPU"
    - resourceType: "Microsoft.Network/virtualNetworks"
      metrics:
        - "Under DDos attack or not"