management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus

resource-discovery:
  interval-in-millis: 300000

scrape:
  interval-in-millis: 300000
  granularity-in-mins: 5
  resourceTypeConfigs:
    - resourceType: "Microsoft.Storage/storageAccounts"
      metricNames:
        - "Availability"
        - "Ingress"
    - resourceType: "Microsoft.Compute/VirtualMachines"
      metricNames:
        - "CPU"